export var ComptrollerErrorCodes;
(function (ComptrollerErrorCodes) {
    ComptrollerErrorCodes[ComptrollerErrorCodes["NO_ERROR"] = 0] = "NO_ERROR";
    ComptrollerErrorCodes[ComptrollerErrorCodes["UNAUTHORIZED"] = 1] = "UNAUTHORIZED";
    ComptrollerErrorCodes[ComptrollerErrorCodes["COMPTROLLER_MISMATCH"] = 2] = "COMPTROLLER_MISMATCH";
    ComptrollerErrorCodes[ComptrollerErrorCodes["INSUFFICIENT_SHORTFALL"] = 3] = "INSUFFICIENT_SHORTFALL";
    ComptrollerErrorCodes[ComptrollerErrorCodes["INSUFFICIENT_LIQUIDITY"] = 4] = "INSUFFICIENT_LIQUIDITY";
    ComptrollerErrorCodes[ComptrollerErrorCodes["INVALID_CLOSE_FACTOR"] = 5] = "INVALID_CLOSE_FACTOR";
    ComptrollerErrorCodes[ComptrollerErrorCodes["INVALID_COLLATERAL_FACTOR"] = 6] = "INVALID_COLLATERAL_FACTOR";
    ComptrollerErrorCodes[ComptrollerErrorCodes["INVALID_LIQUIDATION_INCENTIVE"] = 7] = "INVALID_LIQUIDATION_INCENTIVE";
    ComptrollerErrorCodes[ComptrollerErrorCodes["MARKET_NOT_ENTERED"] = 8] = "MARKET_NOT_ENTERED";
    ComptrollerErrorCodes[ComptrollerErrorCodes["MARKET_NOT_LISTED"] = 9] = "MARKET_NOT_LISTED";
    ComptrollerErrorCodes[ComptrollerErrorCodes["MARKET_ALREADY_LISTED"] = 10] = "MARKET_ALREADY_LISTED";
    ComptrollerErrorCodes[ComptrollerErrorCodes["MATH_ERROR"] = 11] = "MATH_ERROR";
    ComptrollerErrorCodes[ComptrollerErrorCodes["NONZERO_BORROW_BALANCE"] = 12] = "NONZERO_BORROW_BALANCE";
    ComptrollerErrorCodes[ComptrollerErrorCodes["PRICE_ERROR"] = 13] = "PRICE_ERROR";
    ComptrollerErrorCodes[ComptrollerErrorCodes["REJECTION"] = 14] = "REJECTION";
    ComptrollerErrorCodes[ComptrollerErrorCodes["SNAPSHOT_ERROR"] = 15] = "SNAPSHOT_ERROR";
    ComptrollerErrorCodes[ComptrollerErrorCodes["TOO_MANY_ASSETS"] = 16] = "TOO_MANY_ASSETS";
    ComptrollerErrorCodes[ComptrollerErrorCodes["TOO_MUCH_REPAY"] = 17] = "TOO_MUCH_REPAY";
    ComptrollerErrorCodes[ComptrollerErrorCodes["SUPPLIER_NOT_WHITELISTED"] = 18] = "SUPPLIER_NOT_WHITELISTED";
    ComptrollerErrorCodes[ComptrollerErrorCodes["BORROW_BELOW_MIN"] = 19] = "BORROW_BELOW_MIN";
    ComptrollerErrorCodes[ComptrollerErrorCodes["SUPPLY_ABOVE_MAX"] = 20] = "SUPPLY_ABOVE_MAX";
})(ComptrollerErrorCodes || (ComptrollerErrorCodes = {}));
export var CTokenErrorCodes;
(function (CTokenErrorCodes) {
    CTokenErrorCodes[CTokenErrorCodes["NO_ERROR"] = 0] = "NO_ERROR";
    CTokenErrorCodes[CTokenErrorCodes["UNAUTHORIZED"] = 1] = "UNAUTHORIZED";
    CTokenErrorCodes[CTokenErrorCodes["BAD_INPUT"] = 2] = "BAD_INPUT";
    CTokenErrorCodes[CTokenErrorCodes["COMPTROLLER_REJECTION"] = 3] = "COMPTROLLER_REJECTION";
    CTokenErrorCodes[CTokenErrorCodes["COMPTROLLER_CALCULATION_ERROR"] = 4] = "COMPTROLLER_CALCULATION_ERROR";
    CTokenErrorCodes[CTokenErrorCodes["INTEREST_RATE_MODEL_ERROR"] = 5] = "INTEREST_RATE_MODEL_ERROR";
    CTokenErrorCodes[CTokenErrorCodes["INVALID_ACCOUNT_PAIR"] = 6] = "INVALID_ACCOUNT_PAIR";
    CTokenErrorCodes[CTokenErrorCodes["INVALID_CLOSE_AMOUNT_REQUESTED"] = 7] = "INVALID_CLOSE_AMOUNT_REQUESTED";
    CTokenErrorCodes[CTokenErrorCodes["INVALID_COLLATERAL_FACTOR"] = 8] = "INVALID_COLLATERAL_FACTOR";
    CTokenErrorCodes[CTokenErrorCodes["MATH_ERROR"] = 9] = "MATH_ERROR";
    CTokenErrorCodes[CTokenErrorCodes["MARKET_NOT_FRESH"] = 10] = "MARKET_NOT_FRESH";
    CTokenErrorCodes[CTokenErrorCodes["MARKET_NOT_LISTED"] = 11] = "MARKET_NOT_LISTED";
    CTokenErrorCodes[CTokenErrorCodes["TOKEN_INSUFFICIENT_ALLOWANCE"] = 12] = "TOKEN_INSUFFICIENT_ALLOWANCE";
    CTokenErrorCodes[CTokenErrorCodes["TOKEN_INSUFFICIENT_BALANCE"] = 13] = "TOKEN_INSUFFICIENT_BALANCE";
    CTokenErrorCodes[CTokenErrorCodes["TOKEN_INSUFFICIENT_CASH"] = 14] = "TOKEN_INSUFFICIENT_CASH";
    CTokenErrorCodes[CTokenErrorCodes["TOKEN_TRANSFER_IN_FAILED"] = 15] = "TOKEN_TRANSFER_IN_FAILED";
    CTokenErrorCodes[CTokenErrorCodes["TOKEN_TRANSFER_OUT_FAILED"] = 16] = "TOKEN_TRANSFER_OUT_FAILED";
    CTokenErrorCodes[CTokenErrorCodes["UTILIZATION_ABOVE_MAX"] = 17] = "UTILIZATION_ABOVE_MAX";
})(CTokenErrorCodes || (CTokenErrorCodes = {}));
